### ISSUE TITLE
How do I use

### ISSUE THREAD

**Issue by marioacalderon** [SyedMuradAliShah/codeigniter-3-files-creator#1]
How do I use

**Comment by SyedMuradAliShah** [comment]
Method 1: Open Visual Studio Code, Press: <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>X</kbd>, extension manager sidebar will be open, After that search **Codeignter 3 Files Creator** or *syed murad* and you will find this extension as this extension is recently build so it will take a little time to get popular. So till that you can use my author name to search it in VScode.
![Searched by Syed Murad](https://user-images.githubusercontent.com/55234974/109082519-faca7680-7725-11eb-8bfd-c268800ba6ff.png)


Method 2: Go and download the extension from [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=SyedMuradAliShah.codeigniter-3-files-creator).
Then Open Visual Studio Code, <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>X</kbd>, extension manager sidebar will be open, on the right top of the sidebar you will see <kbd>...</kbd> (three dots button) click on it and **Install from VSIX**, then choose the downloaded file and install it. 
![Install from VSIX](https://user-images.githubusercontent.com/55234974/109082528-00c05780-7726-11eb-9d9c-39a9edb8f290.png)

**Comment by marioacalderon** [comment]
it's great! 

Thank you very much from Colombia.

**Comment by SyedMuradAliShah** [comment]
It's completely my pleasure, I would love it if you leave your review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=SyedMuradAliShah.codeigniter-3-files-creator&ssr=false#review-details). And express your thought over there, It will help me and this extension to become popular. ❤️
