### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by wlwtvr** [SyedMuradAliShah/codeigniter-3-files-creator#2]
Extensions not working. 

Steps:
1. Install extensions through marketplace
2. Press F1
3. Try running `> CI3 make:model` or any other CI3 command

Result:
![image](https://user-images.githubusercontent.com/4457089/150557563-c444f927-8322-4f9a-9af5-6f5a7b457444.png)

Expected result:
Model created. or command working

**Comment by wlwtvr** [comment]
Found the culprit. The extensions is fail to activate because it can't find mLibrary module.
Looks like there is typo in filenaming mLibrary module. 

Solutions: rename `mlibrary.js` file to `mLibrary.js` (with capital L)

**Comment by wlwtvr** [comment]
Made a PR #3 to fix this, if you don't mind.

**Comment by SyedMuradAliShah** [comment]
> Found the culprit. The extensions is fail to activate because it can't find mLibrary module. Looks like there is typo in filenaming mLibrary module.
> 
> Solutions: rename `mlibrary.js` file to `mLibrary.js` (with capital L)

Thanks for reporting, your pull request has been approved. An update will appear on the marketplace.
